export const tokens = {
    color: {
        bgDeep: '#0a0a0b',
        bgSurface: '#111113',
        bgElevated: '#1a1a1d',
        bgInteractive: '#242428',
        accentPrimary: '#6366f1',
        accentGlow: '#818cf8',
        accentMuted: '#4f46e5',
        textPrimary: '#fafafa',
        textSecondary: '#a1a1aa',
        textTertiary: '#71717a',
        borderSubtle: '#27272a',
        borderActive: '#3f3f46',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#06b6d4',
    },
    typography: {
        display: '"Space Grotesk", system-ui, sans-serif',
        body: '"Space Grotesk", system-ui, sans-serif',
        mono: '"Space Mono", monospace',
    },
    radius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
    },
    motion: {
        ease: 'cubic-bezier(0.4, 0, 0.2, 1)',
        fast: 150,
        normal: 250,
    },
};